backend = "xrender";
vsync = true;

# Transparencia básica
fading = true;
fade-in-step = 0.03;
fade-out-step = 0.03;
fade-delta = 3;

detect-client-opacity = true;
use-ewmh-active-win = true;
detect-transient = true;
use-damage = false;
log-level = "warn";

rules = (
    { match = "focused"; opacity = 1; },
    { match = "!focused"; opacity = 0.85; }
);

